name: lint

on:
  push:
    paths:
      - '**.php'
      - 'pint.json'
      - '.github/workflows/lint.yml'
  pull_request:
    paths:
      - '**.php'
      - 'pint.json'
      - '.github/workflows/lint.yml'

jobs:
  pint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          coverage: none
      - uses: ramsey/composer-install@v4
      - name: Run Pint
        run: vendor/bin/pint --test
